# Copyright Hyperledger Aries contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)

trigger: none

pr:
- master

jobs:
  - job: PR_check
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - script: |
          set -ex
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CE7709D068DB5E88
          sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb bionic master"
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get -qq update
          sudo apt-get -qq install -y -q libindy
        displayName: 'install libindy'

      - script: |
          set -ex
          yarn
          yarn install --dev jest
        displayName: 'install pre-reqs, jest'

      - script: |
          set -ex
          npm pack
          yarn add file:aries-framework-javascript-1.0.0.tgz
        displayName: 'npm pack aries'

      - script: |
          set -ex
          yarn test -t "agents"
        displayName: 'yarn test, No networking'

      - script: |
          set -ex
          ./run.sh alice >/dev/null 2>/dev/null &
          sleep 10
          ./run.sh bob >/dev/null 2>/dev/null &
          sleep 10
          if [ "" == "${AGENT-PUBLIC-DID-SEED}" ]; then echo "Missing environment variable test-did-seed"; exit 1 ;fi
          TEST_AGENT_PUBLIC_DID_SEED=${AGENT-PUBLIC-DID-SEED} yarn test --forceExit
        displayName: 'yarn test, networking'

