name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  TEST_AGENT_PUBLIC_DID_SEED: 000000000000000000000000Trustee9
  GENESIS_TXN_PATH: network/genesis/local-genesis.txn

jobs:
  integration-test:
    runs-on: ubuntu-18.04
    name: Integration Tests
    steps:
      - name: Checkout aries-framework-javascript
        uses: actions/checkout@v2

      - name: Get docker cache
        uses: satackey/action-docker-layer-caching@v0.0.5

      - name: Start indy pool
        run: |
          docker build -f network/indy-pool.dockerfile -t indy-pool .
          docker run -d --name indy-pool -p 9701-9708:9701-9708 indy-pool
          docker exec indy-pool indy-cli-setup

      - name: Register DID on ledger
        run: docker exec indy-pool add-did-from-seed "${TEST_AGENT_PUBLIC_DID_SEED}"

      - name: Build framework docker image
        run: docker build -t aries-framework-javascript .

      - name: Start mediator agents
        run: docker-compose up -d

      - name: Run tests
        run: >-
          docker run 
          --network host
          --name framework-jest-tests 
          --env TEST_AGENT_PUBLIC_DID_SEED=${TEST_AGENT_PUBLIC_DID_SEED}
          --env GENESIS_TXN_PATH=${GENESIS_TXN_PATH}
          --env DEBUG=aries-framework-javascript
          aries-framework-javascript 
          yarn test

      - name: Export docker logs
        if: always()
        run: |
          mkdir logs
          docker-compose logs --no-color > logs/docker-mediator-agents.log
          docker logs framework-jest-tests > logs/docker-framework-jest-tests.log

      - name: Upload docker logs
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: docker-logs
          path: logs
